#                    STOP!
# -------Do not edit this file directly-------
# -----Edit ~/.bash_profile.custom instead----
# Only edit this file to update the whole repo

# Run multiple Python versions on same machine
eval "$(pyenv init -)"
export PYENV_VIRTUALENVWRAPPER_PREFER_PYVENV="true"
export WORKON_HOME=$HOME/virtualenvs
pyenv virtualenvwrapper_lazy

# Python package manager
export PATH="$HOME/.poetry/bin:$PATH"

# Add Visual Studio Code (code)
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

# Iterm2 advanced features
test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

# Docker autocompletion
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

# Git autocompletion
[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"

# Github cli setting
eval "$(hub alias -s)"
if [ -f ~/cmd_settings/hub.bash_completion ]; then
  . ~/cmd_settings/hub.bash_completion
fi

# Handy aliases
alias ls="ls -CF"
alias lah="ls -lah"
alias myip="curl http://ipecho.net/plain; echo"

function cs () {
    cd "$@" && ls
}

function mcd () {
    mkdir -p $1
    cd $1
}

source ~/.bash_profile.custom.sh
