#                    STOP!
# -------Do not edit this file directly-------
# ---Edit ~/.shell_profile.custom.sh instead--
# Only edit this file to update the whole repo

# Iterm2 advanced features
test -e "${HOME}/.iterm2_shell_integration.bash" && source "${HOME}/.iterm2_shell_integration.bash"

# Docker autocompletion
[ -f /usr/local/etc/bash_completion ] && . /usr/local/etc/bash_completion

# Git autocompletion
[[ -r "/usr/local/etc/profile.d/bash_completion.sh" ]] && . "/usr/local/etc/profile.d/bash_completion.sh"

source ~/.shell_profile.sh
