#!/bin/bash

#                    STOP!
# -------Do not edit this file directly-------
# ---Edit ~/.profile.custom.sh instead--
# Only edit this file to update the whole repo

# Run multiple Python versions on same machine
eval "$(pyenv init -)"
export PYENV_VIRTUALENVWRAPPER_PREFER_PYVENV="true"
export WORKON_HOME=$HOME/virtualenvs
pyenv virtualenvwrapper_lazy

# Python package manager
export PATH="$HOME/.poetry/bin:$PATH"

# Add Visual Studio Code (code)
export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"

# Rust package manager
export PATH="$HOME/.cargo/bin:$PATH"

# Github cli setting
eval "$(hub alias -s)"
if [ -f ~/cmd_settings/hub.bash_completion ]; then
  . ~/cmd_settings/hub.bash_completion
fi

# Handy aliases
alias myip="curl http://ipecho.net/plain; echo"

function cs () {
    cd "$@" && ls
}

function mcd () {
    mkdir -p $1
    cd $1
}

source ~/.profile.custom.sh
