name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: ludeeus/action-shellcheck@2.0.0
        with:
          severity: warning

  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - uses: mfinelli/setup-shfmt@v4.0.1
      - uses: dprint/check@v2.3

  shellharden:
    name: Shellharden
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2
      - run: |
          curl -fsSL https://github.com/anordal/shellharden/releases/download/v4.3.1/shellharden-x86_64-unknown-linux-gnu.tar.gz | tar -xz
          sudo mv shellharden /usr/local/bin/
      - run: shellharden --check **/*.sh
